# Site settings
title: 兴超@iite的技术博客
email: xingchao.liu@iite.com
description: > #兴超@iite的技术博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pandacc.github.io" # the base hostname & protocol for your site
twitter_username: xingchao.liu@iite.com
github_username:  pandacc

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 兴超@iite
  email: xingchao.liu@iite.com
  link: http://pandacc.github.io
  weibo: http://weibo.com/
  github: http://github.com/pandacc
title: 兴超@iite的技术博客                             #自定义常量

# avatar头像及Favicon
avatar: https://avatars2.githubusercontent.com/u/15904669?v=3&s=460
#favicon: https://avatars2.githubusercontent.com/u/15904669?v=3&s=460

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: redcarpet                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置

ba:
  src: //hm.baidu.com/hm.js

# disqus 设置
disqus:
  shortname: 